version: "3.7"
services:
  hilla-javers:
    build: .
    environment:
      SPRING_DATA_MONGODB_HOST: mongo-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: hilla-javers
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:4.4.3
    ports:
      - "27017:27017"
    restart: always
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    #      DB_VENDOR: POSTGRES
    #      DB_ADDR: postgres
    #      DB_DATABASE: keycloak_db
    #      DB_USER: ${POSTGRES_USER:-postgres}
    #      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    #      KEYCLOAK_USER: admin
    #      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
  #    depends_on:
  #      - postgres
